### ISSUE TITLE
幕课的失效啦，跪求重新分享下

### ISSUE THREAD

**Issue by superguopeng** [maskleo/learning-resources#3]

**Comment by maskleo** [comment]
@superguopeng   已更新链接

**Comment by superguopeng** [comment]
还是打不开呀

**Comment by maskleo** [comment]
@superguopeng 链接：https://pan.baidu.com/s/17ZUOYpjuSzCgu6NUPwo3qQ 密码：5l8c

**Comment by superguopeng** [comment]
动脑学院vip的连接、java秒杀系统方案优化高性能高并实战 和精通高级RxJava 2响应式编程思想 失效啦，能否再分享下

**Comment by maskleo** [comment]
有问题请开新的 issues
