### ISSUE TITLE
failed to open git/github resources. 资源文件不存在

### ISSUE THREAD

**Issue by gokejian** [maskleo/learning-resources#4]

**Comment by maskleo** [comment]
请问是哪个链接

**Comment by gokejian** [comment]
此链接， 谢谢  https://pan.baidu.com/s/1m_SSXLDY-1HGZylUO-Zmbw
[cid:5F939457-DED4-4137-9A33-96DE730D5BCF]


On Sep 9, 2018, at 8:54 PM, maskleo <notifications@github.com<mailto:notifications@github.com>> wrote:


请问是哪个链接

**Comment by maskleo** [comment]
具体是哪个资源？
